name: CI/CD

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: TestWorkflowApp

    steps:
    - name: "Check out code"
      uses: actions/checkout@v3

    - name: "Setup dotnet"
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6
    
    - name: "Install dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build

    - name: Run app
      run: | 
       dotnet run "Github Runner" "test"
