name: CI/CD

on:
  workflow_dispatch:
  repository_dispatch:
    types: [tenant_creation_event]

jobs:
  run-app:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: TestWorkflowApp

    steps:
    - name: "Print payload"
      run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'

    - name: "Check out code"
      uses: actions/checkout@v3

    - name: "Setup dotnet"
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6
    
    - name: "Install dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build

    - name: "Run app"
      run: | 
       dotnet run github.event.client_payload.environment github.event.client_payload.databaseName
